spring:
  profiles:
    include: local-db
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health  # /actuator/health 엔드포인트만 노출