#spring:
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: ${DB_URL}
#    username: root
#    password: ${DB_PASSWORD}
#custom:
#  jwt:
#    secretKey: ${JWT_SECRET_KEY}
#  admin-secret-key: ${ADMIN_SECRET_KEY}