name: Deploy to Ec2 Develop

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Github Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Create application-dev.yml
        run: echo "${{ secrets.APPLICATION_DEV_PROPERTIES }}" > ./src/main/resources/application-dev.yml

      - name: Create application-credentials.yml for test
        run: echo "${{ secrets.APPLICATION_TEST_CREDENTIALS }}" > ./src/test/resources/application-credentials.yml

      - name: Set up Docker for Testcontainers
        run: |
          sudo systemctl start docker  # Docker 데몬 실행
          docker --version  # Docker가 정상 실행되는지 확인

      - name: Run Tests with Gradle
        run: ./gradlew test
        env:
          TESTCONTAINERS_RYUK_DISABLED: true  # Ryuk 비활성화로 실행 속도 향상
          TESTCONTAINERS_CHECKS_DISABLE: true # 불필요한 체크 비활성화

      - name: Test and Build
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      - name: Change build result file name
        run: mv ./build/libs/*SNAPSHOT.jar ./project.jar

      - name: Copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_DEV_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_DEV_PRIVATE_KEY }}
          source: project.jar
          target: /home/ubuntu/backend/tobe

      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_DEV_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_DEV_PRIVATE_KEY }}
          script_stop: true
          script: |
            rm -rf /home/ubuntu/backend/current
            mkdir /home/ubuntu/backend/current
            mv /home/ubuntu/backend/tobe/project.jar /home/ubuntu/backend/current/project.jar
            cd /home/ubuntu
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar /home/ubuntu/backend/current/project.jar --spring.profiles.active=dev > ./output.log 2>&1 &
            rm -rf /home/ubuntu/backend/tobe
