name: PR_test.yml

on:
  pull_request:
    branches:
      - develop

jobs:
  gradle-test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Github Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Create application-credentials.yml for test
        run: echo "${{ secrets.APPLICATION_TEST_CREDENTIALS }}" > ./src/test/resources/application-credentials.yml

      - name: Set up Docker for Testcontainers
        run: |
          sudo systemctl start docker  # Docker 데몬 실행
          docker --version  # Docker가 정상 실행되는지 확인

      - name: Run Tests with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean test --no-daemon --info
        env:
          TESTCONTAINERS_RYUK_DISABLED: true  # Ryuk 비활성화로 실행 속도 향상
          TESTCONTAINERS_CHECKS_DISABLE: true # 불필요한 체크 비활성화
#          GRADLE_OPTS: "-Xmx4g"
#          JAVA_TOOL_OPTIONS: "-Xmx4g"
